### ISSUE TITLE
Basic hardware monitoring

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#11]
interface for monitoring (available DFEs, running DFEs, discuss with Maxeler)

Deadline: 2 weeks (mid of June)
Split along with #24

**Comment by gregorychrysos** [comment]
We implemented the script that monitors the available and the running DFEs of the Maxeler server. The next thing is to define an interface between the monitoring layer and  our script. Is there any way that you prefer? E.g. We can provide you with a Java code that will open socket with the Maxeler server and will return the number of available DFEs. Is it a valid solution?

**Comment by eichelbe** [comment]
Yes, let's start with that :) We can then take the code over into the Monitoring layer as a specific monitoring module ;)

**Comment by gregorychrysos** [comment]
We put the code for a basic hardware monitoring process in the SVN at this path:
/qualimaster/trunk/hardware/WP3/Monitoring. You need just the monitor code, as the monitor server code will run on the Maxeler server (Olynthos)...

If you need any help on this code, just tell us!

**Comment by eichelbe** [comment]
Thanks ;) We will have a look at it in the next days...

**Comment by eichelbe** [comment]
I did a first integration round of the code into the Monitoring Layer (not committed). Two questions:
- Can the number of available (maximum of free) DFEs change at runtime, e.g., by disabling a defect DFE? If yes, it would also be good to have the actual available number of DFEs.
- do you really need two ports for the communication with the server. We just need to know this, as this will go into the configuration and before we extend the model ... ;)

**Comment by npav** [comment]
If using a single port seems like a more appealing case, I guess we can switch to a single port model where the client also sends an extra "identification" message to the server saying whether the client is a Receiver or Transmitter.

**Comment by eichelbe** [comment]
The background of this question was that typically network connections such as sockets implicitly work in both directions, i.e., unifying Transmitter and Receiver on the same socket leaving the protocol as it is could do the job. But it's actually only a question and in your decision, as for us the only difference is whether we have two ports in the configuration or only one ;)

**Comment by npav** [comment]
I get what you mean, though the idea is that we have one Transmitter of data, one Receiver of results, and one server (that is essential both a Receiver and Transmitter at the same time).
So, it is not the case where we can have a single pair of Transmitter-Receiver so the communication cannot be handled by a single socket as there are two types of clients.
Our alternatives are:
1) Use a different communication port for each type of client
2) Use a single port and make the clients send an identification message onConnect

I believe either one would work fine.

**Comment by eichelbe** [comment]
What are the two types of clients?

**Comment by npav** [comment]
Okay I think I have highjacked your thread-issue and I am talking about an entirely different topic and I just figured out. I was talking about the hardware integration subtopology, while you are obviously talking about monitoring the available DFEs. Sorry for the misunderstanding...

**Comment by eichelbe** [comment]
No problem. Interesting ;) Let's clarify the question with the availability (can DFE's change at runtime) with Gregory first, i.e., whether we need a second value. Then, we take your final implementation (either two or one port), integrate it into the Monitoring Layer (as an extension of the actual integration) and test it [last test failed as HW Server seemed to be down].

**Comment by gregorychrysos** [comment]
As far as about the available DFEs. There are always 4 available DFEs and if they are not locked by a process, then we consider them as free, available and not defected. We can either send you the information about the  number of not defected DFEs or you can consider them as a stable number(4). (Beside that we did not have the chance :-) :-) to "meet" a defected DFE till now!) 
Also, we will try a single port for communication. We will prepare the new version and we will upload it later in the day.

**Comment by eichelbe** [comment]
Fine. We will take the 4 available DFEs as part of our MPCCNode element in the configuration and keep this constant at runtime. Looking forward to the new version ;)

**Comment by eichelbe** [comment]
@cuiqin could you please add the monitoring port to the MPCCNode in ReconfigurableHardware.ivml?

**Comment by cuiqin** [comment]
As mentioned from Gregory, I've added a single port for MPCCNode. If we need this to be multiple, let me know.

**Comment by eichelbe** [comment]
As far as I remember, Oliver told us in Bremen that we shall also consider the number of available / free CPUs. Is this still relevant, as we have it in the model and in D4.1?

**Comment by eichelbe** [comment]
HW base information is now taken over from the configuration. However, testing is not possible as the HW is down ;)

**Comment by eichelbe** [comment]
Integrated: Detailed as well as summarized monitoring.
Extended: Connection check for Jenkins, as it is as a DMZ machine not allowed to connect to other machines outside.

**Comment by gregorychrysos** [comment]
We put the new code for the hardware monitoring process in the SVN at this path:
/qualimaster/trunk/hardware/WP3/Monitoring_1_port/. 

We changed the code in order to use just a single port for our communication. Is there anything else to be done from our side? 

Thank you!

**Comment by gregorychrysos** [comment]
Also, I forgot to say that we are running the new server on the Olynthos Maxeler server, so you can test it if you want.

**Comment by eichelbe** [comment]
Thanks. Just the question whether the number of CPUs is somehow relevant (Olivers idea in Bremen). If not, then we just need to test it and we are done ;)

**Comment by gregorychrysos** [comment]
I thing that the number of CPUs is not relevant. The Qualimaster pipeline has the number of the available DFEs as resources. The restrictions on the number of the used CPUs can be internally solved by the Mexeler server OS. I don't know if that answers the question! :-)

**Comment by eichelbe** [comment]
Ok, you are the hardware expert ;) Then we will remove the CPUs consistently from the model (no problem to add them again if needed), include the new version and try it out. We will let you know ;)

**Comment by eichelbe** [comment]
Integrated new monitoring - works, against olynthos as well as a local fake junit test server. Works from Jenkins, i.e., DMZ connection restrictions are considered :)

Removed CPU monitoring mapping for rt-VIL.

We consider cleaning up the configuration model for hardware regarding CPUs, might be we need this somehow for the general purpose machines in order to support better balancing of pipelines. Let's see.

Ready to close the task? ;)
