### ISSUE TITLE
HW-Integration: Check sub-topology

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#20]
Check whether a single bolt with threading is ok or whether we need bolt + spout.

**Comment by eichelbe** [comment]
As discussed in Chania, a single Bolt might not be sufficient as output can only happen if execute is called and we go for now with bolt + spout (but no more Storm components). If a single Bolt is not possible at all, please close this issue with a respective comment.

**Comment by npav** [comment]
Exactly, a single bolt is not sufficient due to the asynchronous nature of the data flow.
