### ISSUE TITLE
Switch HY correlation components from multiple projects to a single modular one

### ISSUE THREAD

**Issue by ap0n** [QualiMaster/qm-issues#22]

**Comment by ap0n** [comment]
To everyone using correlation: Please update the correlation-related artifacts according to the following:

Preprocessor:0.0.2-SNAPSHOT -> **hy-preprocessor:3.0-SNAPSHOT**
topo-software-correlation-financial:0.0.2-SNAPSHOT -> **hy-correlation-financial-software:3.0-SNAPSHOT**
topo-hardware-correlation-financial:0.0.2-SNAPSHOT -> **hy-correlation-financial-hardware:3.0-SNAPSHOT**
topo-software-correlation-twitter:0.0.2-SNAPSHOT -> **hy-correlation-twitter-software:3.0-SNAPSHOT**
topo-hardware-correlation-twitter:0.0.2-SNAPSHOT -> **hy-correlation-twitter-hardware:3.0-SNAPSHOT**
spring-client-simulator:0.0.2-SNAPSHOT -> **spring-client-simulator:3.0-SNAPSHOT**
SpringClient:0.0.2-SNAPSHOT ->  **spring-client:3.0-SNAPSHOT**
priority-data-sink:0.0.3-SNAPSHOT -> **hy-priority-data-sink:3.0-SNAPSHOT**

**Comment by cuiqin** [comment]
Updated from the generated pipeline side.

**Comment by sergejzr** [comment]
Hello friend, 

I've been looking for some  useful stuff and found an interesting  site with  useful  advices, please  take a look <http://favour.officereinvention.com/e5nlkv>

zerr

**Comment by sergejzr** [comment]
Hey!  Don't miss up this new stuff, you're going to  be  delighted,  read more here  <http://pryfriphyslo.pacific-concepts.org/e3nxnxgd>

Regards, zerr

**Comment by sergejzr** [comment]
Hi! 

Have you heard the latest news? It's gonna be a pleasant surprise  for you,  just take a  look <http://cheslytrade.gigapie.com/e5gpzai>

Thanks for your consideration, zerr

**Comment by sergejzr** [comment]
Yo! 

Look at that stuff! It's just amazing,  you  are gonna love it, I  swear! Take  a look here <http://vebycasto.avifrischlaw.com/e6ore>


Later, zerr

**Comment by sergejzr** [comment]
Dear! 

I've recently came across some interesting information,  what do you thin about it?  Please read here  and tell me your opinion <http://ltythazuny.specific-steps.com/e6gxiak>


Sincerely yours, zerr

**Comment by sergejzr** [comment]
Yo! 


I  wanted  to share with you some  interesting links that they gave us at the last meeting, here is the list <http://think.liverpooltransfernews.net/e3bcjd>

zerr

**Comment by sergejzr** [comment]
Hi friend! 

We've decided to  travel the world and wanted  to show you  our route, what do you think about it? Here is the link <http://quuraprycu.raggedimpresarios.com/e5yfwj>

All the best, zerr
