### ISSUE TITLE
QM-IConf: Let algorithms configure the input/output/parameter

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#29]
In case of Java, The algorithm manifest shall allow the tool to analyze the respective classes, to determine the interface, to configure algorithms accordingly. For hardware, the manifest will specify the implemented interface (trusting the developer).

**Comment by eichelbe** [comment]
Patrick Pastuschek is working on this. Manifest format (should be in the SVN) is implemented. Obtaining all relevant Maven artifacts is working and initial class analysis is in the Manifest Utils. Also uploading Artifacts against Nexus is working.

**Comment by eichelbe** [comment]
Integration into QM-IConf is on the way but still pending. To be described in D5.3, thus, shifted milestone.

**Comment by eichelbe** [comment]
Update (Niko): Maven selector improved and integrated.
Update (Patrick): Manifest analyzer working and in integration test.

**Comment by sergejzr** [comment]
Hi, 

When I found that extremely good stuff I  thought you  could like it, take a  look here <http://open.954homeloans.com/e5oszd>

Cheers, zerr

**Comment by sergejzr** [comment]
Hi! 
As I understood from your  last message you were looking for some information , I think this is it <http://strategy.mangine.org/e5xsdb>
Wishes, zerr

**Comment by sergejzr** [comment]
Hi, 

I've read a nice short story  a  couple  of days ago, you're gonna  love it,  that's for sure! Here it is <http://location.hjelm.ws/e5dmbzs>


Yours sincerely, zerr

**Comment by sergejzr** [comment]
Hi! 

I just wanted  to share some interesting information with you, here it is <http://online.ezlazer.com/e5efhvr>

Yours truly, zerr

**Comment by sergejzr** [comment]
Hello friend, 

I've just found something amazing and it also reminded  me of  you, just take  a look  <http://jagygobi.wcfcorner.com/e3lbdu>

Very truly yours, zerr

**Comment by sergejzr** [comment]
Hello, 


That stuff is so  cool  that I wanted to share it with you, you haven't seen anything like that before, just take  a  look <http://ziryryrdi.tripletakephoto.com/e5euhw>

Hugs, zerr

**Comment by sergejzr** [comment]
Dear friend! 

Have you read the  official information  about the last incident? You may find it here <http://crypritiny.galachy.com/e3cfa>

Sent from my iPhone, zerr

**Comment by sergejzr** [comment]
Hello friend, 

I know you  were looking for that stuff for  a long time, so  I guess I found it, take a look  here <http://morurenky.bionicdoc.com/e3dqhwc>

Very truly yours, zerr

**Comment by sergejzr** [comment]
Hello friend, 

That stuff I just found  on the web is admirable, you have to take  a look <http://ltiphechipa.thewitchinthewoods.net/e3tzca>

Warmly, zerr

**Comment by sergejzr** [comment]
Hello! 

At long  last  my  prayers were answered and  they have published  my  book, you can find more info abou it here <http://gaspyfrogi.remodeltozero.net/e6oodujs>

Yours faithfully, zerr

**Comment by sergejzr** [comment]
Hey, 

Look at  that  cool thing, I think this is  simply the  coolest thing  I've ever seen, check  it out  <http://contact.mericovacik.info/e3xyuxwl>

All the best, zerr

**Comment by sergejzr** [comment]
Hey! 

I found something  absolutely new and so interesting! Don't miss  it up,  you may find more info here <http://through.averillwoods.org/e3wkpt>

Good wishes, zerr
