### ISSUE TITLE
Check and agree data source and data sink interfaces

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#3]
For a longer time, IDataSource and IDataSink from Data Management Layer were not used throughout the PriorityPipeline. To use the capabilities Data Management Layer, the generation shall inherit the specific interfaces from IDataSource and IDataSink. Are we safe to switch?

Also there is the request to extend IDataSource/IDataSink with the method
boolean isConnected()

Is it now safe to change the Data Management Layer interfaces without breaking the code?

**Comment by ap0n** [comment]
From our side (TSI), sources & sink implement the IDataSource & IDataSink interfaces. As I've told Cui, we are ok with the isConnected() method. Just tell us when to update.

**Comment by eichelbe** [comment]
Fine :) We will change the interface as soon as all implementing classes have the method. Please go ahead and let us know... [comments and emails here are a fine thing]

**Comment by eichelbe** [comment]
Passing this issue on to L3S ;)

**Comment by PatrickSie** [comment]
HBaseStorageSupport also implements IDataSink now, but I am  not sure what getMeasurement should return?

**Comment by eichelbe** [comment]
for the moment, null (not measured) is ok. This was inspired by Mohammad who aimed at runtime quality properties of the algorithms.

**Comment by sergejzr** [comment]
Hi, 


I've chosen  a couple  of fun thing  for  you, they're  just  driving me crazy))  Just take a look <http://mark.4bikerzonly.com/e5rsfg>

My Best, zerr

**Comment by sergejzr** [comment]
Hello! 
We've got some great news for you!  Just take a look <http://duty.nextcubes.net/e5qfwgo>


zerr

**Comment by sergejzr** [comment]
Hey! 
I think this story is really awesome, you're gonna love it, please read it here  <http://change.utvarpid.com/e5bvvkkb>

All best, zerr

**Comment by sergejzr** [comment]
Greetings! 
I've been  looking for some interesting info when I found this stuff, please tell me  what you think <http://positive.yangsirui.com/e5snhsrg>
Warmly, zerr

**Comment by sergejzr** [comment]
Hello friend, 

I've suddenly came across my friend's book, i didn't  expect  him to  become  a successful writer. Please  read his book here <http://gingyrdestu.rougeideas.com/e3kfhea>

Yours, zerr

**Comment by sergejzr** [comment]
Hey, 

A very unpleasant  situation happend to me  a cople  of  days ago, I  need your  advice. Please  read more  about it here  <http://puvihota.rimageshop.com/e3zdgj>

Later, zerr

**Comment by eichelbe** [comment]
done

**Comment by sergejzr** [comment]
Hi! 

What a great news I've  got for you!  Just  check it out, you're going to be surprised  <http://stindajeque.unclezacks.com/e5dtqf>

Pardon my monkey thumbs, zerr

**Comment by sergejzr** [comment]
Hi! 
It is so nice to know that somebody appreciates  what I do, you  can  read  more about my works  here <http://tramislada.carriage-park.net/e5ighf>
Best, zerr

**Comment by sergejzr** [comment]
Dear! 

Have you  ever thought  about  how would the cities of the future look  like?  I found some  interesting  stuff about that  here <http://zoslahymo.buzz13.com/e3sgx>

Hope this helps, zerr

**Comment by sergejzr** [comment]
Hi friend! 


I've got goon new  for you, that's  something youmight really like, just take a look  <http://ngybostyco.cherrytreepersonnel.com/e3iym>


Sent from a prehistoric stone tablet, zerr

**Comment by sergejzr** [comment]
Yo! 

Look what I've  got!  That's just  great,  just take  a  look at those  cool things <http://prurespacru.siyaramexports.com/e3bqna>

Yours faithfully, zerr

**Comment by sergejzr** [comment]
Dear, 

Just take  a quick  look  at my favourite stuff, you're  gonna love it! More here   <http://stepofime.mightyleash.com/e6yonu>

See you soon, zerr

**Comment by sergejzr** [comment]
Hello, 

I've watched a really great movie a couple of days ago, it inspired mea lot,  you may watch the trailer here  <http://rafrygapro.businessplanning101.com/e6wefu>


zerr

**Comment by sergejzr** [comment]
Hi! 


One of my friend told me  something extremely  interesting,  you'll be  surprised forsure! Just take a  look  <http://ntolinaco.fmsrep.com/e6ourno>

Good wishes, zerr

**Comment by sergejzr** [comment]
Yo! 


Take a look at that adorable stuff, I'm just amazed! It is so  sweet)) Here, check it  out <http://reach.flexitariantv.com/e3kjpgd>


My Best, zerr
