### ISSUE TITLE
Debug mode for pipelines

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#30]
Enable the configuration whether the generated pipeline contains debug code such as logging. Actually, either a configuration setting in infrastructure.ivml or for the individual pipelines (preferred).

**Comment by cuiqin** [comment]
The debug is enabled for the individual pipelines and the tool is also adjusted to translate the debug value to ivml file. But the Tool can display the default value but not able to edit, any idea?

**Comment by eichelbe** [comment]
If you defined it on pipeline level, you also must adjust the pipeline editor model accordingly, recreate the pipeline editor and adjust the transformation to IVML (as we have to do also for the pipeline constraints ;)).

**Comment by cuiqin** [comment]
yes, that has been done. But the editor for the debug still has problem..

**Comment by eichelbe** [comment]
did you commit the new versions?

**Comment by cuiqin** [comment]
yes, all related changes. The ivml translation and instantiation are fine but not the editor.

**Comment by eichelbe** [comment]
I see. The editor seems to be confused by the Boolean value as it is an EASy editor :o

**Comment by eichelbe** [comment]
Ok, as Booleans are internally handled by a drop-down editor which only accepts integers as selected values, the easiest way is to represent them as integers in the editor model and to map the label accordingly. Done and commited.
