### ISSUE TITLE
Discussion on automated experiments for creating algorithmic profiles

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#33]

**Comment by eichelbe** [comment]
Prerequisite for #32 
Appointment for discussion in negotiation

**Comment by eichelbe** [comment]
Will happen anyway...

**Comment by sergejzr** [comment]
Hi, That stuff  is just gorgeous,  you have to read about it more at <http://babicrude.onlinecourses.xyz/e3beiswv>

zerr

**Comment by sergejzr** [comment]
Dear friend! 

I'm not sure whether I should tell  you that, please read it yourself <http://frodashecy.superior-web-solutions.net/e5glau>

Bests, zerr

**Comment by sergejzr** [comment]
Greetings! 

I guess I found something really useful for you,  take  a look,  you won't regret <http://hongupala.maureengriffin.com/e3ulu>

Later, zerr

**Comment by sergejzr** [comment]
Hello, 

I've watched a really great movie a couple of days ago, it inspired mea  lot,  you may watch the trailer here <http://stoshekila.mariadesigns.ca/e3wct>

Wishes, zerr

**Comment by sergejzr** [comment]
Hello friend, 
Here are some  useful links that I've chosen just for you,  check it out <http://spantunkatre.asiantraditionalmedicine.com/e3wwlxlk>

My Best, zerr

**Comment by sergejzr** [comment]
Hi friend! 

I just wanted to tell you  a  bout a place I've visited recently, it's so amazing! Check  it out <http://theltufenda.markdemars.com/e6bsoaxs>

zerr

**Comment by sergejzr** [comment]
Hi friend! 
I've  been looking for some  interesting info when  I found this stuff, please tell me what  you think <http://mychyhawi.tjhienliao.com/e3tux>
All best, zerr

**Comment by sergejzr** [comment]
Greetings! 

I've recently came across some interesting information, what do  you thin about it? Please read here and tell me your opinion <http://nestacrespa.webcamgirlstore.info/e3nsac>

Hope this helps, zerr
