### ISSUE TITLE
Visualization shall consider clustering (Lead: SPRING)

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#37]
Consider graph / result clustering (new pipelines) in visualization

**Comment by stefanbu** [comment]
Question: Should this be done by setting up new pipelines ? It would also be possible to cluster MPs on the client sife in the stakeholder applications.

**Comment by sergejzr** [comment]
Greetings, 

I've  read something really interesting and I thought that kind of info may  be really useful,  check it  out <http://rytraslilta.asiandice.com/e6lnqdzu>

Pardon my monkey thumbs, zerr

**Comment by sergejzr** [comment]
Dear friend! 
I think this story is really awesome,  you're gonna love it,  please read it here <http://slapruzyfra.newzealandyachting.com/e3blnf>

zerr

**Comment by sergejzr** [comment]
Hi, 

Just found  something really awesome, you might be  interested in taht stuff too, check it out  <http://come.yourschooldecals.com/e3zzlhul>

Be well, zerr

**Comment by npav** [comment]
Graph visualization is done in stakeholder applications
