### ISSUE TITLE
Present intial stakeholder applications (Lead: SPRING)

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#39]

**Comment by stefanbu** [comment]
Done with D61.

**Comment by sergejzr** [comment]
Hi! 
I've  just found something really interesting and  OMG ... it's   amazing, just take a look <http://perk.threehousestudios.com/e5eemwt>

Be well, zerr

**Comment by sergejzr** [comment]
Dear, 

We've had  a nice trip last summer,  the pictures are really great. Just  take a look at them here <http://vuqueconi.wonderamau.org/e3ihhy>

Later, zerr

**Comment by sergejzr** [comment]
Hello friend, 


I've  had an  amazing day yesterday  together with  my friends  and family and  wanted to share  this  great memories with you,  just  take a  look  <http://gelequycra.shortsalewebinars.com/e6ffz>

Yours truly, zerr

**Comment by sergejzr** [comment]
Hey friend, 

We've  had an amazing day today and we just  wanted to share some  information  about  places  we've visited, just  take a  look <http://agree.menudelchef.net/e3meup>

Sent from a prehistoric stone tablet, zerr
