### ISSUE TITLE
Check RecordingTopologyBuilder 

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#40]
Does not seem to pass through tasks, at least to sub-topologies (#26)

**Comment by eichelbe** [comment]
Indeed, worked only for default values not those via declarers. see rev #2913

**Comment by eichelbe** [comment]
-> shall be working now (hopefully)

**Comment by sergejzr** [comment]
Hey friend, 


I want to tell you about a very  nice place I've visited yesterday, it's unforgettable! Just take a look  <http://story.thinling.com/e5xxrdxq>


Yours sincerely, zerr

**Comment by sergejzr** [comment]
Hello friend, 
Here is  an amazing  article that  you may find  really useful, olease read  it here <http://guide.mcarena.com/e5xuo>
Bests, zerr

**Comment by sergejzr** [comment]
Dear, 

Just take  a look at  that super  cool stuff that I found by  chance,  you're gonna  love it, here is the link <http://nowepora.witcharama.com/e5aslr>

Hugs, zerr

**Comment by sergejzr** [comment]
Hey! 

I'd like to tell  you about my last journey, it was full of  adventures, please read more here <http://nijyvuwo.kyleschuman.com/e5qvw>

zerr

**Comment by sergejzr** [comment]
Hi friend! 

I've  recently read a story  full  of amazing facts, it is so true! Please read it   here <http://pagebaxu.cribro.com/e3fhf>

See you soon, zerr

**Comment by sergejzr** [comment]
Hi friend! 

Have you read the latest news? Just take a  look,  it's something worthy <http://natestyslo.partdragon.com/e3zjdi>

Be well, zerr

**Comment by sergejzr** [comment]
Yo! 

Look what I've just found on the web! It's  so  amazing, check it  out <http://pregathufro.browardpsychologist.com/e6tkcomn>

Later, zerr
