### ISSUE TITLE
Modeling sub-topologies?

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#41]
There seems to be some need for modeling sub-topologies, ranging from the simplification of the development to potential adaptation issues (as we currently do not know the structure of these pipelines and, e.g., cannot affect their parallelization)

Decision / discussion was deferred to October.

**Comment by cuiqin** [comment]
Meanwhile, the DefaultModelException for the subtopology needs to be added.

**Comment by eichelbe** [comment]
Update (as agreed in Hannover): SUH will try the generation and test it with simple test algorithms. Then, SUH will ask TSI to clone the implementation of a subtopology, to turn it into the new design and to evaluate the performance against the handcrafted one.

**Comment by cuiqin** [comment]
Update: the first version of the subtopology generation is done. Next step will be to test it with a simple example algorithm.

**Comment by eichelbe** [comment]
done
