### ISSUE TITLE
Simple pass-through algorithm for analysis

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#42]
As discussed by email (sorry, I forgot to list)
- a simple integer-to-integer pass-through algorithm in Hardware (or on host machine)
- one integer parameter for delay tuples (in ms, can be done on host machine)
- if possible, also one parameter for aggregation (int, if 1 - just pass through, if 2 - pass only each second tuple, etc).
- for testing uploading and pipeline-effects

**Comment by eichelbe** [comment]
under development, debugging, evaluation

**Comment by gregorychrysos** [comment]
This has finished as far as I know! :-) :-) :-)
