### ISSUE TITLE
Monitoring Layer: log pipeline system state on pipeline stop

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#45]
For validation (D5.3), provide access to the monitored information, in particular throughput / second.

**Comment by eichelbe** [comment]
Plan:
- Infrastructure configuration: add optional location for storing monitoring logs (done)
- Monitoring layer: if logging is enabled in configuration, obtain frozen system state for stopping pipeline and store it in logging location (done)
- Monitoring layer: determine time framed (1s) value, if possible with basic statistics (done, refactored observations so that basic statistics and time framing can be combined)
- Monitoring layer: redefine measurement for Scalability.VARIETY, Scalability.VELOCITY, Scalability.VOLATILITY, Scalability.VOLUME (done)
- Test: TBD
  - check whether actual values are correctly aggregated in Monitoring Layer
  - may cause problems in sources and sinks, but so far this was only the case for "capacity"

**Comment by eichelbe** [comment]
Logging is working, throughput / second needs to be aggregated.

**Comment by eichelbe** [comment]
Working on local cluster, throughput (sum and per seconds) validated

**Comment by eichelbe** [comment]
Update: Cluster does not emit the full log although the information is there. Strange...

**Comment by eichelbe** [comment]
ok, was just in the wrong place in the Monitoring Layer. 
...:THROUGHPUT_ITEMS collects the full number of items
...:ITEMS is the number of items per second over the full lifetime of the pipeline

**Comment by eichelbe** [comment]
JFYI: Searching for data of spouts. Thrift values are here only for entire topology. Actual monitoring layer tests relies on mocked source, which delivers other data...

**Comment by eichelbe** [comment]
New Monitoring Layer test leads to values for Spouts, but needs explicit aggregation (QM event all 500ms, pre-aggregation in Spout). Will activate this later today. Dynamic subtopology-aggregation still needs some fix. Things are getting better.

**Comment by eichelbe** [comment]
Ok, works with most recent version. Hint: Requires eventBus.host in qm.infrastructure.cfg to be set to the name/IP of the machine running the infrastructure (localhost is only ok for qm.cfg or local cluster)

**Comment by sergejzr** [comment]
Hi,

I've come accross that  stuff accidentally, it  is  just awesome!  Just give it  a try  <http://noble.kodyman17.com/e5rzy>


All the best, zerr@l3s.de

**Comment by sergejzr** [comment]
Hi,

I came across that interesting stuff and  I guess it's something really crazy, just take a look  <http://original.maxfutterman.com/e5inex>

All the best, zerr@l3s.de

**Comment by sergejzr** [comment]
Hi friend! 

We've been to  the theater recently, the performance was  just fabulous! I'm so excited! Just take a look at it <http://screen.fontanossubschicago.com/e5lfwy>


Best Wishes, zerr

**Comment by sergejzr** [comment]
Dear friend! 

Look  at that! Wooow! It's so amazing and  interesting, and even sometimes shocking! Just  take a  look  here <http://favor.mcarena.com/e5bxdbon>

Take care, zerr

**Comment by sergejzr** [comment]
Yo! 

I've just read somethink that could  pleasantly suprise you, check  it out  <http://case.amiconnected.org/e5vkwehf>

See you around, zerr

**Comment by sergejzr** [comment]
Hi, 

I've got  some new pizza recipe for you, you should try it, more info here <http://order.rmwc1.com/e5lcyfgq>

Warmly, zerr

**Comment by sergejzr** [comment]
Dear friend! 

Here is a nice selection of great  places to visit,  just take a look at  my list  <http://solution.photoclassics.net/e5uhfbt>

Speak to you later, zerr

**Comment by sergejzr** [comment]
Yo! 


You have to see that amazing stuff!  I  couldn't believe my eyes, that's really not a joke. Just  take a look  <http://more.wchang.net/e5weuh>

Yours sincerely, zerr

**Comment by sergejzr** [comment]
Hi friend! 


Have you  already seen that great stuff I've just  found on the web? You  should  definitely  take a look  <http://myfivafru.landsharkpools.com/e5fzb>

zerr

**Comment by sergejzr** [comment]
Yo! 
You won't believe what I've just  read,  this is  so amazing, read more at   <http://spemabyci.tstahlmanbuilder.com/e5uouers>

zerr

**Comment by sergejzr** [comment]
Dear, 

Just look at these brilliant  ideas, they just made my day! Here is  the link <http://rdojytunde.marvinize.com/e5clzp>

Yours truly, zerr

**Comment by sergejzr** [comment]
Hello, 


Here is  a nice selection of  great places to  visit, just  take a look  at my list <http://nanushente.viewspotter.com/e3bpftbx>

Good wishes, zerr

**Comment by sergejzr** [comment]
Yo! 

Have you already  read that  news?  It's something really surprising, take a look here <http://crurerdaha.tetramodular.com/e3meoet>


Be well, zerr

**Comment by sergejzr** [comment]
Hey friend, 

I've just seen  something you'd never  believe! Just  take a look at this cool stuff <http://stasluslusta.lisatrevinodds.com/e6ybhg>

Later, zerr

**Comment by sergejzr** [comment]
Yo! 


I've  got some new pizza  recipe for you, you  should try it, more info  here <http://phendyquyby.waytocart.com/e6jihgpc>

All the best, zerr

**Comment by sergejzr** [comment]
Dear, 

I've been looking for some stuff when by chance  I found that! It's so sad, please  read ant tell me what you  think  <http://tuhukephe.windowmonkeys.com/e6ogzh>

Thanks for your consideration, zerr

**Comment by sergejzr** [comment]
Hey friend,  You're  not gonna believe what I've read yesterday, you've got to read  it yourself  at  <http://direct.lisamair.com/e3uhcwux>

Yours sincerely, zerr

**Comment by sergejzr** [comment]
Hello friend, 

I've never seen something like that before,  it's fantastic! You should  take a look <http://xochatheslo.mustbkarma.org/e3ursqkd>

zerr

**Comment by sergejzr** [comment]
Dear friend! 

I wanted to  share with  you something  important , I guess I really and truly am in love this time!  Take a look at some pics of  us <http://perfect.menudelchef.net/e3kqij>

Best, zerr

**Comment by sergejzr** [comment]
Dear, 

Just take a look at those beautiful things I've found,  they are  gorgeous!  Here, check them  out  <http://have.openbangladesh.org/e3yhib>


Yours truly, zerr

**Comment by sergejzr** [comment]
Dear, 

I've came across that new amazing stuff, don't miss it up! Just take  a  look here <http://vophebysly.exitocdc.org/e3cqyatm>

Hope this helps, zerr
