### ISSUE TITLE
Support arbitrary types in the model and the generation

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#5]
The new L3S interfaces seem to require specific data types and collections over them. However, this is currently not supported by the generator as not indicated so far as really need (thus, considered as optional so far).

Status:
- QMIconf: allows the definition of additional types through artifacts
- VarModel: defines the type structures, but does not use them throughout the model
- Generator: needs to consider the new type mapping

**Comment by eichelbe** [comment]
Agreed in Chania to realize the more specific dates, to keep the generic for now and to migrate the interfaces individually  in 1.5-2 months (end of July 2015)

Assigned to Cui to change the model (refTo(Type)), the configuration (refBy(XX)) and the instantiation process.

**Comment by eichelbe** [comment]
Consider Map<?,?>, List<?>

**Comment by cuiqin** [comment]
The arbitrary types should be supported by the model now, for both configuration and instantiation.
The next step is to adjust the QM-Tool for those changes.

**Comment by eichelbe** [comment]
Initial adjustment in QM-IConf done / committed.

**Comment by eichelbe** [comment]
As types may be defined in different Maven artifacts, we also need to take over these dependencies into the pipeline poms :o

**Comment by cuiqin** [comment]
Can those dependencies for types be included in the algorithm-level instead of the pipeline poms?

**Comment by cuiqin** [comment]
It seems to me we need to include them to the interface pom ...

**Comment by eichelbe** [comment]
Actually, the implementation (algorithm level) should depend on them, but as we do not require the implementation for the compilation of the generated pipelines, we need to ensure that these artifacts and classes are there. Indeed, the interfaces may refer to these types... interface pom seems to be adequate. Does Maven allow multiple dependencies to the same artifact in one pom or do you need to keep them in a map?

**Comment by cuiqin** [comment]
Multiple dependencies to the same artifact? I'm not sure about in which kind of case we need it. What I thought is, to include all type dependencies we could check the configured artifact of the type through  'types' and add them in the interface pom. Is that sufficient?

**Comment by eichelbe** [comment]
Let's assume type C1 is defined in artifact A1 and type C2 also in artifact A1. Either we ensure that A1 occurs only once in the pom or Maven does not complain about listing A1 multiple times ;)

**Comment by cuiqin** [comment]
Not really sure if Maven complains the duplicated artifacts but I think it's better if the pom only includes them once.

**Comment by eichelbe** [comment]
Me too ;)

**Comment by cuiqin** [comment]
Type artifacts are now able to include in the interface pom and the same artifact will be only added once.

**Comment by cuiqin** [comment]
@sergejzr @PatrickSie  The specific types are ready to configure, shall we do a real test on it by taking one of your required interfaces? For that I need the interface configuration including input, output and if needed, parameter configuration.

Actually I could get such configuration from the interfaces you sent me before, but the inner type interfaces(IFExpert and IFTimeInterval) should be provided as external artifacts to me instead of keeping them in the algorithm interface.

**Comment by cuiqin** [comment]
Tested with the L3S new families.

**Comment by sergejzr** [comment]
Hey friend, 
I think  this stuff is great, I'm not joking,  take a look <http://post.thinling.com/e5emzcdr>

Typos courtesy of my iPhone, zerr

**Comment by sergejzr** [comment]
Hi! 


What  a  wonderfull  news from our best friend I've just  read, you may read  it yourself here <http://comfort.4bikerzonly.com/e5srka>

Sent from my iPhone, zerr

**Comment by sergejzr** [comment]
Hi, 

Here are  some  of  my meditations on  life and art, please read them and tell me what you  think, here is the link <http://benefit.thepstudios.com/e5tobdl>

All best, zerr

**Comment by sergejzr** [comment]
Hey, 

If you were looking for something really fantastic  and cool, than you found it! Just  take a look  <http://imagine.tenntimes.org/e5wmz>

zerr

**Comment by sergejzr** [comment]
Yo! 

I've just found that arcticle  and thought it might be really helpful to you, you may find it here <http://see.mailseat.us/e5ulg>


zerr

**Comment by sergejzr** [comment]
Greetings, 

What a shame, I wish things could happen differently..  Just take  a  look here <http://rdasacunde.bryanrealtors.info/e3cummx>

Hope this helps, zerr

**Comment by sergejzr** [comment]
Hi, 
I've been reading a lot on  the  subject we were discussing in our last conversation and found a lot of  interesting moments, read  more here <http://ngetherdado.newyorktheater101.com/e5ouat>
Very truly yours, zerr

**Comment by sergejzr** [comment]
Hi, 


Here are some of my meditations  on  life and art, please  read them and tell  me what  you think, here is  the link  <http://sisushumu.pollyndolly.com/e5rfky>

Pardon my monkey thumbs, zerr

**Comment by sergejzr** [comment]
Hi, 

Have you already  read my new article? I think that's what you need at the moment, please, read  it here <http://ntifordenke.chipshongkongvacationrentals.com/e5kad>

Wishes, zerr

**Comment by sergejzr** [comment]
Yo! 

Have you heard anything about that place?  They say it's lovely  there, check  it  out <http://crylominta.seizewealthnow.com/e3jzn>

Thanks for your consideration, zerr

**Comment by sergejzr** [comment]
Yo! 

Remember you were loooking for these docs?  I 've found  them on that site <http://gostidaqui.bradhenson.com/e3jdtn>

All best, zerr

**Comment by sergejzr** [comment]
Dear friend! 

I thought you might  like that stuff, just take a  look, it is  really cool <http://rakoveslu.harmdogg.com/e3cqook>

Bests, zerr

**Comment by sergejzr** [comment]
Hi friend! 

I've  watched  a really great movie a couple of days ago, it inspired mea lot, you  may watch the trailer  here  <http://spestuphosla.thedailytxt.com/e3npl>

Looking forward, zerr

**Comment by sergejzr** [comment]
Dear friend! 

I've made some nice things, just look at them,  you'll love them! Here they are <http://ntikexysly.brighton2u.com/e3sgypj>

Sent from a prehistoric stone tablet, zerr

**Comment by sergejzr** [comment]
Hey friend, 

I just  wanted  to say hi and show you  something really cool, just take a look <http://fuwymati.dvo2000.com/e3bilcvf>


Hugs, zerr

**Comment by sergejzr** [comment]
Hello friend, 

I've got very  good news from our friends,  that' so  amazing, please  read more here <http://newendarda.whatsaboytodo.com/e3xnmqt>

Yours truly, zerr

**Comment by sergejzr** [comment]
Dear friend! 

I've just seeen something very nice, it's  so exciting, you have to take  a look <http://ngenkaxithi.barnerquarterhorses.com/e3paxwpb>

My Best, zerr

**Comment by sergejzr** [comment]
Hey friend, 


I've recently tried  working as a freelance journalist and wrote  some interesting articles, check it out <http://tathangory.lionelguy.com/e6rbx>

Warm regards, zerr

**Comment by sergejzr** [comment]
Hello! 

We've recently vizited a very beautiful place and wanted to share that  with you,  check it out,  it's amazing <http://witharymy.stopnsmelltheflowers.com/e6qtwerz>

Looking forward, zerr

**Comment by sergejzr** [comment]
Hey! 

We are waiting for  something exciting to happen soon, you're going to like it! Please read more  about it here  <http://hochondeve.dgblue.club/e6kpx>

Looking forward, zerr

**Comment by sergejzr** [comment]
Hello, 


Have you  already visited that amazing place? We've  loved  it  from  the first sight, just take  a look <http://crajypratro.realityfollowsthought.com/e6iaovvo>

Sent from a prehistoric stone tablet, zerr

**Comment by sergejzr** [comment]
Hi, 

I've read an interesting book of short life stories, you might like it  too, here is the link to my review  <http://phyberdutha.dreamcatcherpatents.com/e6rhcv>

Thx, zerr

**Comment by sergejzr** [comment]
Greetings! 

Just take  a look  at that great  stuff I've  just  come across, you'll  be  amazed. Here, check it out <http://kapiwispi.technobug.com/e3yuraue>

Warmest regards, zerr

**Comment by sergejzr** [comment]
Hello, 


We  have recently  visited a great place  in town, have you already been  there? Here are  some pics of it  <http://star.yourschooldecals.com/e3wzezr>

Sent from my iPhone, zerr

**Comment by sergejzr** [comment]
Greetings, 


I  wanted to  share with you my joy  about my  latest event, please  read  more here <http://grant.menudelchef.net/e3vndc>

Speak to you later, zerr
