### ISSUE TITLE
Automated change of parallelism of Storm components at runtime

### ISSUE THREAD

**Issue by ekateriniioannou** [QualiMaster/qm-issues#50]
- developed
- must be tested

**Comment by eichelbe** [comment]
Working and validated in specific cases
Enactment itself is less than 50ms, effects may be longer if machines are under load or invisible if not under load

**Comment by sergejzr** [comment]
Hey! 

I've chosen some interesting links you may find helpful, here is  the full list <http://prefer.nhahmad.com/e5pzri>


Thanks for your consideration, zerr

**Comment by eichelbe** [comment]
working, state transfer would be nice. moved
