### ISSUE TITLE
Use the same source in different pipelines concurrently

### ISSUE THREAD

**Issue by ap0n** [QualiMaster/qm-issues#57]
Use different accounts for spring API

**Comment by stefanbu** [comment]
These accounts for spring API can be used (let me know, if you need more):

Username:
tsi1
tsi2
tsi3
tsi4
tsi5

Password for all: password

Regards,
Stefan

Am 11.12.2016 um 10:42 schrieb Apostolos Nydriotis:

**Comment by npav** [comment]
@eichelbe If I am not mistaken, you suggested having a default parameter with the account name for each source, right? If yes, how would that work for the same source being used in different pipelines? The parameters are defined on the algorithm level, not on the pipeline level, so if we define a default parameter account for a source, it will use the same in both pipelines. Am I missing something?

**Comment by eichelbe** [comment]
Right. There was somewhen a discussion with LUH to have a family of sources/sinks and it seems that I mixed that up. Alternatives to solve that (further ideas are welcome):
- Extend the configuration of data sources/sinks to define specific default values for the underlying implementation element overriding the default value there. Although conceptually better, I would like to  avoid this form of change now.
- A processing element does not receive the pipeline name it is running within (just sub-topologies). Allowing this would require a change of interfaces. Alternative would be an additional on-top interface (as for IScalableTopology) to pass this information to elements requiring this information and a respective change to the generation/infrastructure. 
- ...

**Comment by npav** [comment]
Well, if we only need it for this case, I could modify the implementations of the sources to pick an account, probe it to see if it already in use, and if so, pick a different one. So, in this case, you don't have to modify interfaces/generation/infrastructue.
The question is : Should we do this "hack", or is there the possibility to also need this functionality elsewhere.

**Comment by eichelbe** [comment]
Ok, if you can figure out this, it would be a kind of round-robin testing. Simple extension with more infrastructure support could be to "lock" an account in the account management requiring to correctly unlock it after use. But for now, I'm fine with both if we can avoid too many changes (we have already enough changes for the switch on top of loose pipelines - except for a network problem, nearly running)

**Comment by npav** [comment]
Okay, I will give it a try this way and let you know.

**Comment by npav** [comment]
Hi Stefan @stefanbu,

Seems like the accounts you issued are not working. I get "wrong password"
for all of them.
("sent data : tsi1,login,password!")

Could you check this please?

Regards,
Nick

**Comment by npav** [comment]
The SpringClient (and also the FocusedSpringClient that uses a SpringClient internally) now dynamically change Spring accounts if the one they chose is already logged in. Tested with two FocusedSpringClients at the same time and working.
