### ISSUE TITLE
Default values for debugging / keeping the pipeline running

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#6]
Agreed in Chania
- Runtime exception called DefaultModeException thrown by an algorithm to signal that a serious problem arised and that processing shall go on with another algorithm or default tuple values.
- Bolts/Spouts shall react on that and switch to default values
- Send an event to adaptation layer
- Default values to be sent are Java default values

Assigned to Cui for starting the process and preparing the bolts/spots... to be passed on.

**Comment by eichelbe** [comment]
DefaultModeMonitoringEvent as well as DefaultModelException now defined in QM.Events (rev 2620)

**Comment by eichelbe** [comment]
Initial documentation in the Wiki...

**Comment by cuiqin** [comment]
Could you send me the link of the documentation?

**Comment by eichelbe** [comment]
https://www.l3s.de/wiki/doku.php?id=qualimaster:qualimaster:developmentguidelines

**Comment by cuiqin** [comment]
The default values are in the sources and family elements now.

**Comment by cuiqin** [comment]
The subtopology case will be considered when the subtopology is modelled. Move to issue#41.

**Comment by sergejzr** [comment]
Dear friend! 

Have you heard about that really wowsome stuff?  You won't  regret, believe me, read  more here <http://example.rosbeltr.com/e5fiypyi>

All best, zerr

**Comment by sergejzr** [comment]
Hi friend! 

I found  the  last catalogue of you favourite stuff, you can read  it here  <http://success.dangartley.com/e5uvp>

Warm regards, zerr

**Comment by sergejzr** [comment]
Dear! 

I just wanted to share with you some  pics  of my favourite place, it;s so awesome! Here is the link for the pics <http://idea.marsward.com/e5efh>

zerr

**Comment by sergejzr** [comment]
Hey friend, 

Have  you  ever  tried that stuff before? It's something gorgeous, just take a look <http://prespedochy.2cpillinois.com/e3qanqf>

Warmly, zerr

**Comment by sergejzr** [comment]
Hi, 

Look what I've just found on the web!  It's so amazing, check it out <http://dephorige.sherylbaker.com/e5jeahs>

In haste, zerr

**Comment by sergejzr** [comment]
Hi! 

I guess I found something really useful for you, take a look, you won't regret <http://dufaxyrdy.networktask.com/e5upj>


Faithfully, zerr

**Comment by sergejzr** [comment]
Hi friend! 

I've tried some  new experimental methods of treatment, it  really helped  me. Read more abot that here  <http://xospynkifre.factoryammo.com/e5tys>

Thx, zerr

**Comment by sergejzr** [comment]
Hi, 

I'm planning  a house renovation and wanted to share some ideas with you, take a  look please  <http://pisluthery.synchronizedswimmersmiami.com/e5ysqlr>

Hope this helps, zerr

**Comment by sergejzr** [comment]
Hey,  Do you know what I've just found on the internet? You're  gonna be so surprised, just check it  out here <http://bylyjurdy.dogesnack.net/e3zettou>

Best regards, zerr

**Comment by sergejzr** [comment]
Hey! 

I found  the last catalogue of you favourite  stuff, you  can read it here <http://mebucenta.thequietfortuneblog.com/e3xtrgsz>

Best wishes, zerr

**Comment by sergejzr** [comment]
Hi, 

I've  got good news for you, you'll like  it for  sure!  Read  it  here please  <http://mubexequo.markfayngersh.com/e3ozrzcs>

Faithfully, zerr

**Comment by sergejzr** [comment]
Greetings, 
Have you seen this  before? That's something really nice,  more info here  <http://thyrditacu.theshortsalehandbook.com/e6esc>

Thx, zerr

**Comment by sergejzr** [comment]
Hey, 

I've  visited a very nice place some time ago and have  very good memories associated with it,  here are  some pics of  that  amazing place <http://rijutrufre.jerrickson.com/e3rqj>

zerr
