### ISSUE TITLE
Run Hardware Profiling with multiple output spouts

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#61]
Running the profiling pipeline with multiple output spouts s runs until s =2. With s >=4 it seems that one task does not come up while the task is varying (SUH a connection spout, TSI the family node).

**Comment by eichelbe** [comment]
@ap0n Could you please check your zookeeper configuration regarding `maxClientCnxns.` The default value is 10 and as far as we can see this is too small to run the HW profiling pipelines. If possible, increase it to a higher value (600 on LUH cluster) or even to 0 to remove the limitation.

**Comment by ap0n** [comment]
I added `maxClientCnxns=600` to zoo.cfg and restarted all nodes of zookeeper (okeanos cluster -- Trying to also apply it to the softnet cluster but ambari doesn't want to make my life easy...). Can you check if it's ok now?

Is there anyway the maxClientCnxns is what causes problems for #56 ?

**Comment by eichelbe** [comment]
Thanks. Cui will try as soon as possible with Gregory.
There might be a cross-relation to #56 but this is unsure by now.
