### ISSUE TITLE
Run Data Managent Bolt on parallel data flow

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#8]
L3S: Consider shuffle grouping to make data management bolt real parallel to main data flow instead having it in sequence.

**Comment by cuiqin** [comment]
Now the generated topology class is adjusted to run DataManagement Bolt in parallel, i.e., in the PriorityPipeline case, the SentimentAnalysis Bolt emits data to both DataManagement and CorrelationTwitter Bolt but no Bolt subscribes to the DataManagement Bolt.

**Comment by eichelbe** [comment]
Just marked it as ready for testing ;)

**Comment by cuiqin** [comment]
It has been tested from my test pipeline which you could also find the "testDMPip" from the QM-IConf.  But it seems to me calling write method in the DataManagement Bolt causes problem, so for the moment I comment that out.
